#ifndef COMMANDS_H
#define COMMANDS_H

#define MODEM                            0
#define POWER                            1
#define FREQUENCY                        2
#define CALIBRATE                        3
#define CALIBRATE_IMAGE_IN_MHZ           4
#define SET_OCP_VALUE                    5
#define SET_TRIMMING_CAPACITORS          6
#define LORA_CRC                         7
#define LORA_INVERT_IQ                   8
#define LORA_HEADER_TYPE                 9
#define LORA_PLD_LEN                    10
#define LORA_PREAMBLE_LEN_IN_SYMBOLS    11
#define LORA_SPREADFACTOR               12
#define LORA_BANDWIDTH                  13
#define LORA_CODERATE                   14
#define LORA_LDRO                       15
#define LORA_AUTO_LDRO                  16
#define GFSK_PREAMBLE_LEN_IN_BITS       17
#define GFSK_PREAMBLE_DETECT_LEN        18
#define GFSK_NODE_ADDRESS               19
#define GFSK_BROADCAST_ADDRESS          20
#define GFSK_ADDRESS_FILTERING_ON       21
#define GFSK_HEADER                     22
#define GFSK_PLD_LEN                    23
#define GFSK_CRC                        24
#define GFSK_DC_FREE                    25
#define GFSK_BR_IN_BPS                  26
#define GFSK_FDEV_IN_HZ                 27
#define GFSK_PULSE_SHAPE                28
#define GFSK_BW_DSB_PARAM               29
#define GFSK_SYNC_WORD                  30
#define GFSK_CRC_SEED                   31
#define GFSK_CRC_POLYNOMIAL             32
#define GFSK_WHITENING_SEED             33
#define SET_TRANSMIT_TIMEOUT            34
#define READ_TRANSMIT_BUFFER            35
#define SET_TRANSMIT_BUFFER_ADDRESS     36
#define TRANSMIT                        37
#define SET_LORA_SYMBOL_TIMEOUT         38
#define SET_RECEIVE_TIMEOUT             39
#define READ_RECEIVE_BUFFER             40
#define SET_RECEIVE_BUFFER_ADDRESS      41
#define RECEIVE_MODE                    42
#define RECEIVE_MODE_DUTY_CYCLING       43
#define STANDBY_MODE                    44
#define FALLBACK_MODE                   45
#define SLEEP                           46
#define WAKEUP                          47
#define SET_CAD_PARAMS                  48
#define CAD                             49
#define FREQUENCY_SYNTHESIS_MODE        50
#define TX_CONTINUOUS_WAVE              51
#define TX_INFINITE_PREAMBLE            52
#define GET_INTERRUPTS                  53
#define CLEAR_INTERRUPTS                54
#define GET_TIME_ON_AIR                 55
#define GET_API_STATUS                  56
#define GET_CHIP_STATUS                 57
#define GET_DEVICE_ERRRORS              58
#define CHECK_RECEIVE_BUFFER            59
#define CHECK_LORA_PACKET               60
#define CHECK_GFSK_PACKET               61
#define CHECK_PLD_LEN                   62
#define CHECK_PREAMBLE_LEN              63
#define GET_LORA_PARAMS_FROM_HEADER     64
#define GET_PACKET_TYPE                 65
#define GET_LORA_PACKET_STATS           66
#define GET_GFSK_PACKET_STATS           67
#define RESET_PACKET_STATS              68
#define GET_LORA_SYNC_WORD              69
#define GET_GFSK_SYNC_WORD              70  


#endif // COMMANDS_H